+OK 806
Content-Type: multipart/mixed; boundary="------------5sWLTDpPOowcnjH7yr7J87Aq"
Message-ID: <c4f840ee-c91f-4075-9606-5aca6d8f8fca@gmail.com>
Date: Fri,15 Dec 2023 22:00:18 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: h@gmail.com
From: =?UTF-8?B??= <nhi@gmail.com>
Subject: ua la vao project chua

This is a multi-part message in MIME format.
--------------5sWLTDpPOowcnjH7yr7J87Aq
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

test vao project???


--------------5sWLTDpPOowcnjH7yr7J87Aq
Content-Type: text/plain; charset=UTF-8; name="helohelo.txt  "
Content-Disposition: attachment; filename="helohelo.txt  "
Content-Transfer-Encoding: base64

aGVsb2hlbG8=

--------------5sWLTDpPOowcnjH7yr7J87Aq--
.
