+OK 1642
Content-Type: multipart/mixed; boundary="------------5sWLTDpPOowcnjH7yr7J87Aq"
Message-ID: <6c304e8d-4662-4d57-aa39-63ce86810e2b@gmail.com>
Date: Fri,15 Dec 2023 19:53:58 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: h@gmail.com, h1@gmail.com
Cc: cc@gmail.com
From: =?UTF-8?B??= <h@gmail.com>
Subject: my new mail virus

This is a multi-part message in MIME format.
--------------5sWLTDpPOowcnjH7yr7J87Aq
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

test cc, bcc, multiple user and spam


--------------5sWLTDpPOowcnjH7yr7J87Aq
Content-Type: text/plain; charset=UTF-8; name="Vocabulary.txt  "
Content-Disposition: attachment; filename="Vocabulary.txt  "
Content-Transfer-Encoding: base64

Vm9jYWJ1bGFyeQ0KDQpSZWdpc3RyeQ0KTGlicmFyeQ0KVGhlYXRyZQ0KUmVzdGF1cmFudA0KRmFjdWx0eSAob2YgTWVkaWNpbmUp
DQpvbiB0aGUgb3RoZXIvc2FtZS9vcHBvc2l0ZSBzaWRlIG9mDQpvbiB0aGUgbGVmdC1oYW5kIHNpZGUgb2YNCnBhc3MNCnNpdHVh
dGVkDQphaGVhZCBvZg0KYmV5b25kDQpmb3VudGFpbg0KYWNjb21tb2RhdGlvbg0KYmxvY2tzDQphY2NvbW1vZGF0aW9uIGJsb2Nr
cw0KdG93YXJkcw0KDQpndWlkZQ0Kc3RhZGl1bSANCmZsb29yDQpvbiB0aGUgZmlyc3Qvc2Vjb25kL3RoaXJkLi4uIGZsb29yDQpn
byB1cCB0aGUgc3RhaXJzDQp3YWxrIHRocm91Z2gNCmNvcnJpZG9yDQp3YWxrIGRvd24NCm1pZGRsZQ0KaW4gdGhlIG1pZGRsZQ0K
YXQgdGhlIGVuZCBvZg0KdHJvcGhpZXMNCnBob3RvZ3JhcGhzDQppdGVtcyBvZiBjbG90aGluZw0KYW4gaW50ZXJhY3RpdmUgZGlz
cGxheQ0KcG9zdGVycw0KDQpzb3VyY2Ugb2YgDQp1bm5lY2Vzc2FyeQ0KZXhwZW5zZQ0KZnJ1c3RyYXRpb24NCmRlZ3JlZSBvZg0K
Y29uc3VtZXINCmF0dGVudGlvbg0KdGhlIG5lZWQgZm9yIA0KZmFpdGgNCmNvbmZpZGVudA0KY29uZmlkZW5jZQ==

--------------5sWLTDpPOowcnjH7yr7J87Aq--
.
