+OK 2149
Content-Type: multipart/mixed; boundary="------------5sWLTDpPOowcnjH7yr7J87Aq"
Message-ID: <8ee0e4f9-f50c-4f25-8792-eb0ced6d9143@gmail.com>
Date: Sun,10 Dec 2023 12:19:36 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: thuminh@gmail.com
From: =?UTF-8?B?dmNocw==?= <thuminh@gmail.com>
Subject: dfnbgfdfgh

This is a multi-part message in MIME format.
--------------5sWLTDpPOowcnjH7yr7J87Aq
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

hi xin chao tat ca cac ban

--------------5sWLTDpPOowcnjH7yr7J87Aq
Content-Type: text/plain; charset=UTF-8; name="oop.txt  "
Content-Disposition: attachment; filename="oop.txt  "
Content-Transfer-Encoding: base64

LVRodeG7mWMgdMOtbmggY+G7p2EgxJHhu5FpIHTGsOG7o25nIGNo4buJIHRoYXkgxJHhu5VpIGLhu59pIGjDoG5oIHZpIGPhu6dh
IG7Dsy4NCi1wcm90ZWN0ZWQ6IGLhuqNvIHbhu4csIGNo4buJIG3hu58gYuG7n2kgY8OhYyBs4bubcCBjb24NCi1jbGFzcyBkaWFn
cmFtOg0KZ+G7k20gMyBwaOG6p246KDEgcGjhuqduIENhdCB0aGVvIHF1eSB04bqvYyBQYXNjYWwgQ2FzZSkNCnByaXZhdGU6IGTh
uqV1IHRy4burDQpwdWJsaWM6IGThuqV1IGPhu5luZw0KdMOqbiBiaeG6v24ga2nhu4N1IGzhuqFjIMSRw6AgKGNhbWVsQ2FzZSkN
CmJp4bq/biBwcml2YXRlIGPDsyBk4bqldSBn4bqhY2ggZMaw4bubaQ0KOjogdG/DoW4gdOG7rSBwaMOibiBnaeG6o2kgcGjhuqFt
IHZpDQovL0ZvcndhcmQgZGVjbGFyYXRpb24gKHZkOiBjbGFzcyBDYXQ7KTogcGjDoSB0aGFtIGNoaeG6v3UgdsOybmcsIHRoxrDh
u51uZyDEkeG6t3QgdHJvbmcgbWFpbi5oDQotIEjhurFuZyBz4buRIFBJIGzDoCBjw7RuZyBraGFpID0+IGThuqV1IGPhu5luZywg
aOG6sW5nIHPhu5EgcGjhuqNpIGPDsyBn4bqhY2ggZMaw4bubaS4NCi0gSMOgbSB04bqhbzogdHLDuW5nIHTDqm4gbOG7m3AgKENh
dCgpKQ0KLSBIw6BtIGjhu6d5OiB0csO5bmcgdMOqbiBs4bubcCBuaMawbmcgdGjDqm0gZOG6pXUgbmfDoyAofkNhdCgpKQ0KLSBI
w6BtIHThuqFvIHbDoCBow6BtIGjhu6d5IGPDsyB0aOG7gyB04buxIMSR4buZbmcgxJFjIHThuqFvIHbDoCBn4buNaS4NCi0gQ29u
IHRy4buPIHRoaXMgdHLhu48gdOG7m2kgxJHhu5FpIHTGsOG7o25nIMSRYW5nIGdp4buvIMSR4buLYSBjaOG7iQ0KLSB0w6puIGjD
oG0gYuG6r3QgxJHhuqd1IGLhurFuZyDEkeG7mW5nIHThu6suIE7hur91IGLhuq90IMSR4bqndSBi4bqxbmcgZGFuaCB04burIHRo
w6wgbMOgIGjDoG0gZ2V0dGVyDQotVHLDoW5oIHRydXkgY+G6rXAgdHLhu7FjIHRp4bq/cCB0aHXhu5ljIHTDrW5oIChhdHRyaWJ1
dGUpIC0tPiBnZXR0ZXIvc2V0dGVy

--------------5sWLTDpPOowcnjH7yr7J87Aq--
.
